---
params:
   auto_title: "Consistency check"
title: "`r params$auto_title`"
header-includes:
- \usepackage[table]{xcolor}
- \usepackage{booktabs}
output: pdf_document
---

<!-- This is a template that works together with the R-file computer.R to create pdf reports. It was inspired from
https://www.reed.edu/data-at-reed/software/R/markdown_multiple_reports.html and
https://scottishsnow.wordpress.com/2018/08/17/many-reports-from-1-rmarkdown-file/-->

<!-- Note that the title is piped from the accompanying R-file (computer.r) and that the "consistency check" is the default title if nothing is piped. -->

<!-- I had to add the usepackages above or else I get errors due to table options, see: -->
<!-- https://github.com/rstudio/rmarkdown/issues/1384 -->
<!-- https://tex.stackexchange.com/questions/484815/cellcolor-undefined-control-sequence -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r load packages and data}
library(kableExtra) #for more advanced tables
library(dplyr) #for summarizing data in summary table

#Load data for each preprint, preprint_results is the dataframe of results, and "preprint" is the loop variable in computer.r file
result_out <- preprint_results[[preprint]]
```


This is a report of the consistency of reported results in COVID preprint number `r preprint_ID[preprint]`. This preprint was coded on `r last_edited[preprint]` by `r initials[preprint]`, and the check was run on `r Sys.Date()`.


# Summary 

```{r summary table}
#Create a summary table for the looped variable

preprint_summary <- result_out %>% 
  group_by(type_stat) %>% 
  summarize(results = n(),
            incorrect = results - sum(check),
            correct = sum(check),
            percent = round(correct/results*100, 1)) %>% 
  arrange(percent) #order descending by % correct

overall <- data.frame(type_stat = "Overall",
                      results = sum(preprint_summary$results),
                      correct = sum(preprint_summary$correct),
                      incorrect = sum(preprint_summary$incorrect))

overall$percent <- round(overall$correct/overall$results*100, 1)
                      
preprint_summary <- rbind(preprint_summary, overall) 

preprint_summary %>% 
  knitr::kable(booktabs = TRUE,
               col.names = c("Stat. type", "Checked Results",  "Inconsistent", "Consistent", "Consistent (%)" )) %>%
  row_spec(nrow(preprint_summary) - 1, hline_after = TRUE)
```

# Detailed results

```{r}
#Then print the detailed table with highlighted (in)consistencies

result_out <- Filter(function(x)!all(is.na(x)), result_out) #drop only NA rows
options(knitr.kable.NA = '-') #print any remaining NAs as empty cells

#Reorder for output that makes more sense (instead of ordered on type_stat)
result_out <- result_out %>% arrange(check, page)

#Change names for nicer table + add cell highlights
result_out$check <- ifelse(result_out$check == 1, "Consistent", "Inconsistent")
result_out$check <- kableExtra::cell_spec(result_out$check, "latex", color = "black", background = ifelse(result_out$check == "Consistent", "green", "red"))

#fix escapings of _
result_out$type_stat <- gsub("_", "\\\\_", result_out$type_stat) #must be done for escape = FALSE in kable to work
colnames(result_out)[2] <- "Stat. type" #can't have _ in col names when escape = FALSE


#Print table
result_out %>% 
  knitr::kable(booktabs = TRUE, escape = FALSE, format.args = list(big.mark = ","))

```
